AWSTemplateFormatVersion: "2010-09-09"
Description: "This is a solution to all challenges in the IAC module in the udacity course"

Parameters: 
  InstanceType: 
    Type: String
    Default: t3.micro
  AmiID:
    Type: AWS::EC2::Image::Id
    Default: ami-0022f774911c1d690
  Subnet:
    Type: AWS::EC2::Subnet::Id
    Default: subnet-0054ba3162eb45aed

Resources: 
  myWebAccessSG:
    Type: AWS::EC2::SecurityGroup
    Properties: 
      GroupDescription: "Allows only inbound access and unrestricted outbound"
      GroupName: webaccessSG
      VpcId: vpc-07d02e25111e09177
      SecurityGroupEgress: 
        IpProtocol: -1
        FromPort: -1
        ToPort: -1
        CidrIp: 0.0.0.0/0
      SecurityGroupIngress:
         IpProtocol: tcp
         FromPort: 80
         ToPort: 80
         CidrIp: 0.0.0.0/0

  myWebServerInstance:
    Type: AWS::EC2::Instance
    Properties: 
     InstanceType: !Ref InstanceType 
     ImageId: !Ref AmiID
     NetworkInterfaces:
     - AssociatePublicIpAddress: True
       DeviceIndex: "0"
       GroupSet: 
       - !Ref myWebAccessSG
       SubnetId: !Ref Subnet
     UserData:
       Fn::Base64: !Sub |
         #!/bin/bash
         sudo yum update -y
         sudo yum install -y httpd
         sudo systemctl start httpd
         sudo systemctl enable httpd
     