AWSTemplateFormatVersion: "2010-09-09"
Description: "This is a solution to all challenges in the IAC module in the udacity course"

Parameters: 
  vpcCidr:
    Type: String 
    Default: "10.0.0.0/16"
  pubCidr1:
    Type: String 
    Default: "10.0.1.0/24"
  pubCidr2:
    Type: String 
    Default: "10.0.2.0/24"
  privCidr1:
    Type: String 
    Default: "10.0.3.0/24"
  privCidr2:
    Type: String 
    Default: "10.0.4.0/24"
  Net:
    Description: Name for output exports
    Type: String 
    Default: UdacityProject


Resources: 
  udagramVPC:
    Type: AWS::EC2::VPC
    Properties: 
      CidrBlock: !Ref vpcCidr
  udagramIG: 
    Type: AWS::EC2::InternetGateway
    Properties:
      Tags:
      - Key: Project 
        Value: Udagram
  myvpcGWA:
    Type: AWS::EC2::VPCGatewayAttachment
    Properties:
      InternetGatewayId: !Ref udagramIG
      VpcId: !Ref udagramVPC

# Public Subnet config      
  pubSubnet1:
    Type: AWS::EC2::Subnet 
    Properties: 
      CidrBlock: !Ref pubCidr1
      VpcId: !Ref udagramVPC
      AvailabilityZone: !Select [0, !GetAZs ''] 
      MapPublicIpOnLaunch: True 
  pubSubnet2:
    Type: AWS::EC2::Subnet 
    Properties: 
      CidrBlock: !Ref pubCidr2
      VpcId: !Ref udagramVPC
      AvailabilityZone:  !Select [1, !GetAZs '']  
      MapPublicIpOnLaunch: True 
  Nat1EIP:  
    Type: AWS::EC2::EIP 
    DependsOn: myvpcGWA
    Properties: 
      Tags:
      - Key: Description
        Value: Public Nat1 IP
  Nat2EIP:  
    Type: AWS::EC2::EIP 
    DependsOn: myvpcGWA
    Properties: 
      Tags:
      - Key: Description
        Value: Public Nat2 IP
  pubNAT1:
    Type: AWS::EC2::NatGateway
    Properties:  
      AllocationId: !GetAtt Nat1EIP.AllocationId
      SubnetId: !Ref pubSubnet1
  pubNAT2:
    Type: AWS::EC2::NatGateway
    Properties:  
      AllocationId: !GetAtt Nat2EIP.AllocationId
      SubnetId: !Ref pubSubnet2      
  DefaultPubRoute:
    Type: AWS::EC2::Route 
    DependsOn: myvpcGWA
    Properties: 
      RouteTableId: !Ref DefaultPubRT
      GatewayId: !GetAtt  udagramIG.InternetGatewayId
      DestinationCidrBlock: "0.0.0.0/0"
  DefaultPubRT:
    Type: AWS::EC2::RouteTable
    Properties:
      VpcId: !Ref udagramVPC
  pubSubRTA1:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      RouteTableId: !Ref DefaultPubRT
      SubnetId: !Ref pubSubnet1 
  pubSubRTA2:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      RouteTableId: !Ref DefaultPubRT
      SubnetId: !Ref pubSubnet2
  
  # Private subnet config
  privSubnet1:
    Type: AWS::EC2::Subnet 
    Properties: 
      CidrBlock: !Ref privCidr1
      VpcId: !Ref udagramVPC
      AvailabilityZone:  !Select [0, !GetAZs ''] 
  privSubnet2:
    Type: AWS::EC2::Subnet 
    Properties: 
      CidrBlock: !Ref privCidr2
      VpcId: !Ref udagramVPC
      AvailabilityZone:  !Select [1, !GetAZs '']
  privRT1:
    Type: AWS::EC2::RouteTable
    Properties:
      VpcId: !Ref udagramVPC
  priRoute1:
    Type: AWS::EC2::Route 
    Properties:
      RouteTableId: !Ref privRT1
      DestinationCidrBlock: "0.0.0.0/0"
      NatGatewayId: !Ref pubNAT1
  privSubRTA1:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      RouteTableId: !Ref privRT1
      SubnetId: !Ref privSubnet1
  privRT2:
    Type: AWS::EC2::RouteTable
    Properties:
      VpcId: !Ref udagramVPC
  priRoute2:
    Type: AWS::EC2::Route 
    Properties:
      RouteTableId: !Ref privRT2
      DestinationCidrBlock: "0.0.0.0/0"
      NatGatewayId: !Ref pubNAT2
  privSubRTA2:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      RouteTableId: !Ref privRT2
      SubnetId: !Ref privSubnet2


Outputs:
  VpcId: 
    Description: The ID of myVPC
    Value: !Ref udagramVPC
    Export:
      Name: !Sub ${Net}-VPCID
  ElasticIP1:
    Description: The Ip address of EIP1
    Value: !Ref Nat1EIP 
    Export:
      Name: !Sub "${Net}-IPv4a"
  ElasticIP2:
    Description: The Ip address of EIP2
    Value: !Ref Nat2EIP 
    Export:
      Name: !Sub "${Net}-IPv4b"
  PrivSubnetId1:
    Description: The Id of my private subnet1
    Value: !Ref privSubnet1
    Export:
      Name: !Sub "${Net}-privSubnet1" 
  PrivSubnetId2:
    Description: The Id of my private subnet2
    Value: !Ref privSubnet2
    Export:
      Name: !Sub "${Net}-privSubnet2"
  PubSubnetId1:
    Description: The Id of my public subnet1
    Value: !Ref pubSubnet1
    Export: 
      Name: !Sub "${Net}-pubSubnet1"  
  PubSubnetId2:
    Description: The Id of my public subnet2
    Value: !Ref pubSubnet2
    Export: 
      Name: !Sub "${Net}-pubSubnet2"